module.exports = {
	GENRE_FILTER_RECEIVED: "GENRE_FILTER_RECEIVED",
	RATING_FILTER_RECEIVED: "RATING_FILTER_RECEIVED",
	YEAR_FILTER_RECEIVED: "YEAR_FILTER_RECEIVED",
	RESET_FILTERS: "RESET_FILTERS",
	NUM_PAGES_RECEIVED: "NUM_PAGES_RECEIVED",
	PAGE_CHANGE_RECEIVED: "PAGE_CHANGE_RECEIVED"
}