module.exports = {
  SEARCHDATA_RECEIVED: "SEARCHDATA_RECEIVED",
  SINGLEMOVIEDATA_RECEIVED: "SINGLEMOVIEDATA_RECEIVED",
  RESET_STORE: "RESET_STORE",
  RATING_CHANGED: "RATING_CHANGED",
  MASTERLIST_RECEIVED: "BROWSEMOVIE_RECEIVED"
};
