module.exports = {
  SEARCHDATA_RECEIVED: "SEARCHDATA_RECEIVED",
  SINGLEMOVIEDATA_RECEIVED: "SINGLEMOVIEDATA_RECEIVED",
  RESET_STORE: "RESET_STORE",
  RATING_CHANGED: "RATING_CHANGED",
  MASTERLIST_RECEIVED: "BROWSEMOVIE_RECEIVED",
  YOUTUBE_RECEIVED: "YOUTUBE_RECEIVED",
  MOVIELIST_ITEM_RECEIVED: "MOVIELIST_ITEM_RECEIVED",
  MOVIELIST_RECEIVED: "MOVIELIST_RECEIVED",
  OPEN_MOVIELIST: "OPEN_MOVIELIST"
};
